### PR TITLE
fix(can): CAN device to always seek recovery

### PR DESCRIPTION
**Pull request by fouge**
with the introduction of a new thread, the CAN state is polled regularly to ensure that the device will always seek recovery. The callback feature used in the past doesn't seem to be reliable.

fixes ORBP-185

### CODE REVIEW

**Comment by sri9311** [comment]
Can you check the failed build pipeline @fouge?
`region `RAM' overflowed by 1268 bytes`

**Comment by Qbicz** [comment]
There are quite a few thread stack sizes defined in https://github.com/worldcoin/orb-firmware/blob/main/main_board/include/app_config.h
Which ones of them have been tuned? Maybe we can shave off a few kB by tuning some of them or even removing some threads?

**Comment by Qbicz** [comment]
> There are quite a few thread stack sizes defined in [`main`/main_board/include/app_config.h](https://github.com/worldcoin/orb-firmware/blob/main/main_board/include/app_config.h) Which ones of them have been tuned? Maybe we can shave off a few kB by tuning some of them or even removing some threads?

If we find ourselves struggling for memory, we could potentially merge thread from https://github.com/worldcoin/orb-firmware/blob/main/main_board/src/temperature/sensors/temperature.c#L476 and https://github.com/worldcoin/orb-firmware/blob/main/main_board/src/power/battery/battery_ruby.c#L32, gaining 2048 bytes. But I think this would hurt the code readability and clear modularization, so for now maybe it's better to just tune the statically allocated sizes.

**Comment by fouge** [comment]
FYI @sri9311 @Qbicz 
Zephyr has a target named `ram_report` (and `rom_report` as well), which helps to find which symbols are using a lot of RAM and can be reduced. It helped me find that RAM allocated for ISO-TP TX messages is just huge for our use case, so I was able to reduce it :) 

there is also the [puncover](https://github.com/HBehrens/puncover) target.

let's merge https://github.com/worldcoin/orb-firmware/pull/109 before we merge that one.

**Comment by Qbicz** [comment]
> FYI @sri9311 @Qbicz Zephyr has a target named `ram_report` (and `rom_report` as well), which helps to find which symbols are using a lot of RAM and can be reduced. It helped me find that RAM allocated for ISO-TP TX messages is just huge for our use case, so I was able to reduce it :)
> 
> there is also the [puncover](https://github.com/HBehrens/puncover) target.
> 
> let's merge #109 before we merge that one.

Omg `puncover` is gold, with Stack Worst Case Scenario analysis
You can merge #109 and rebase on it :+1:

**Pull request merged**
